paths:
  base_dir: ~/tools-github-learner
  output_dir: learnings

models:
  default_model: gemini-2.5-flash-preview-04-17
  available_models:
    # local
    mlx-community/SmolLM-135M-Instruct-4bit: #smallest
      context_window: 32000
    mlx-community/gemma-3-1b-it-qat-8bit: #small
      context_window: 32000
    mlx-community/gemma-3-12b-it-8bit: #big
      context_window: 128000
    mlx-community/gemma-3-27b-it-qat-4bit: #bigger
      context_window: 128000
    # cloud
    gemini-2.5-flash-preview-04-17: # Google Gemini Flash via API
      context_window: 1114112 # Standard context is ~1M